apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
spec:
  containers:
  - image: mysql:5.6
    name: mysql
    env:
      # $ kubectl create secret generic mysql-pass --from-file=password.txt
      # make sure password.txt does not have a trailing newline
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-pass
          key: test
    ports:
    - containerPort: 3306
      name: mysql
