#cloud-config

---
write-files:
  - path: /etc/conf.d/nfs
    permissions: '0644'
    content: |
      OPTS_RPC_MOUNTD=""
  - path: /opt/bin/waiter.sh
    owner: root
    permissions: 0755
    content: |
      #! /usr/bin/bash
      until curl http://127.0.0.1:2379/v2/machines; do sleep 2; done
  - path: /etc/kube-env
    permissions: 0644
    owner: root
    content: |
      KUBE_VERSION=1.4.5

hostname: master
coreos:
  etcd2:
    name: master
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    advertise-client-urls: http://$private_ipv4:2379,http://$private_ipv4:4001
    initial-cluster-token: k8s_etcd
    listen-peer-urls: http://$private_ipv4:2380,http://$private_ipv4:7001
    initial-advertise-peer-urls: http://$private_ipv4:2380
    initial-cluster: master=http://$private_ipv4:2380
    initial-cluster-state: new
  flannel:
    etcd_servers: http://localhost:2379
    interface: $public_ipv4
  fleet:
    etcd_servers: http://localhost:2379
    metadata: k8srole=master
  locksmithd:
    endpoint: http://localhost:2379
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
    - name: rpc-statd.service
      command: start
    - name: settimezone.service
      command: start
      content: |
        [Unit]
        Description=Set the time zone

        [Service]
        ExecStart=/usr/bin/timedatectl set-timezone America/Sao_Paulo
        RemainAfterExit=yes
        Type=oneshot
    - name: etcd2-waiter.service
      command: start
      content: |
        [Unit]
        Description=etcd waiter
        Wants=network-online.target
        Wants=etcd2.service
        After=etcd2.service
        After=network-online.target
        Before=flanneld.service fleet.service locksmithd.service

        [Service]
        ExecStart=/usr/bin/bash /opt/bin/waiter.sh
        RemainAfterExit=true
        Type=oneshot
    - name: flanneld.service
      command: start
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Service]
            ExecStartPre=-/usr/bin/etcdctl mk /coreos.com/network/config '{"Network": "10.244.0.0/16", "Backend": {"Type": "vxlan"}}'
    - name: kube-apiserver.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes API Server
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        Requires=etcd2-waiter.service
        After=etcd2-waiter.service

        [Service]
        EnvironmentFile=/etc/kube-env
        ExecStart=/usr/bin/rkt --insecure-options=image --net=host run quay.io/coreos/hyperkube:v1.4.5_coreos.0 \
        --exec=/hyperkube -- apiserver \
        --insecure-bind-address=0.0.0.0 \
        --service-cluster-ip-range=10.100.0.0/16 \
        --etcd-servers=http://localhost:2379 \
        --allow-privileged=true
        Restart=always
        RestartSec=10
    - name: kube-controller-manager.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes Controller Manager
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        Requires=kube-apiserver.service
        After=kube-apiserver.service

        [Service]
        EnvironmentFile=/etc/kube-env
        ExecStart=/usr/bin/rkt --insecure-options=image --net=host run quay.io/coreos/hyperkube:v1.4.5_coreos.0 \
        --exec=/hyperkube -- controller-manager \
        --master=127.0.0.1:8080
        Restart=always
        RestartSec=10
    - name: kube-scheduler.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes Scheduler
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        Requires=kube-apiserver.service
        After=kube-apiserver.service

        [Service]
        EnvironmentFile=/etc/kube-env
        ExecStart=/usr/bin/rkt --insecure-options=image --net=host run quay.io/coreos/hyperkube:v1.4.5_coreos.0 \
        --exec=/hyperkube -- scheduler \
        --master=127.0.0.1:8080
        Restart=always
        RestartSec=10
  update:
    group: stable
    reboot-strategy: off
