#cloud-config
write-files:
  - path: /etc/conf.d/nfs
    permissions: '0644'
    content: |
      OPTS_RPC_MOUNTD=""
  - path: /opt/bin/wupiao
    owner: root
    permissions: 0755
    content: |
      #!/bin/bash
      # [w]ait [u]ntil [p]ort [i]s [a]ctually [o]pen
      [ -n "$1" ] && [ -n "$2" ] && while ! curl --output /dev/null \
        --silent --head --fail \
        http://${1}:${2}; do sleep 1 && echo -n .; done;
      exit $?
  - path: /etc/kube-env
    permissions: 0644
    owner: root
    content: |
      MASTER_IP=172.16.0.10
      KUBE_VERSION=1.7.5

coreos:
  etcd2:
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    advertise-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    initial-cluster: master=http://172.16.0.10:2380
    proxy: on
  flannel:
    etcd_endpoints: http://localhost:2379
  fleet:
    etcd_servers: http://localhost:2379
    metadata: k8srole=node
  locksmithd:
    endpoint: http://localhost:2379
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
    - name: flanneld.service
      command: start
    - name: rpc-statd.service
      command: start
    - name: settimezone.service
      command: start
      content: |
        [Unit]
        Description=Set the time zone

        [Service]
        ExecStart=/usr/bin/timedatectl set-timezone America/Sao_Paulo
        RemainAfterExit=yes
        Type=oneshot
    - name: docker.service
      command: start
      drop-ins:
        - name: 39-docker-opts.conf
          content: |
            [Service]
            Environment="DOCKER_OPTS=--log-driver=json-file --log-opt max-size=500M --log-opt max-file=3"
        - name: 40-flannel.conf
          content: |
            [Unit]
            Requires=flanneld.service
            After=flanneld.service
    - name: kubelet.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes Kubelet
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        Requires=network-online.target
        After=network-online.target

        [Service]
        EnvironmentFile=/etc/kube-env
        # wait for kubernetes master to be up and ready
        #rkt-fly Magic from kubelet-wrapper: https://github.com/coreos/coreos-kubernetes/issues/287
        ExecStartPre=/opt/bin/wupiao 172.16.0.10 8080
        ExecStart=/usr/bin/rkt --insecure-options=image --net=host run \
        --volume etc-ssl-certs,kind=host,source=/usr/share/ca-certificates \
        --volume var-lib-docker,kind=host,source=/var/lib/docker \
        --volume var-lib-kubelet,kind=host,source=/var/lib/kubelet \
        --volume os-release,kind=host,source=/usr/lib/os-release \
        --volume run,kind=host,source=/run \
        --mount volume=etc-ssl-certs,target=/etc/ssl/certs \
        --mount volume=var-lib-docker,target=/var/lib/docker \
        --mount volume=var-lib-kubelet,target=/var/lib/kubelet \
        --mount volume=os-release,target=/etc/os-release \
        --mount volume=run,target=/run \
        --stage1-from-dir=stage1-fly.aci \
        quay.io/coreos/hyperkube:v1.7.5_coreos.0 \
        --exec=/hyperkube -- kubelet \
        --api-servers=172.16.0.10:8080 \
        --image-gc-high-threshold=60% \
        --image-gc-low-threshold=30% \
        --system-reserved="memory=500m" \
        --low-diskspace-threshold-mb=1024 \
        --kube-reserved="memory=500m" \
        --eviction-hard="memory.available<500Mi" \
        --maximum-dead-containers=1 \
        --allow-privileged=true \
        --hostname-override=$private_ipv4
        Restart=always
        RestartSec=10
    - name: kube-proxy.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes Proxy
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        Requires=network-online.target
        After=network-online.target

        [Service]
        EnvironmentFile=/etc/kube-env
        # wait for kubernetes master to be up and ready
        #rkt-fly Magic from kubelet-wrapper: https://github.com/coreos/coreos-kubernetes/issues/287
        ExecStartPre=/opt/bin/wupiao 172.16.0.10 8080
        ExecStart=/usr/bin/rkt --insecure-options=image --net=host run \
        --stage1-from-dir=stage1-fly.aci \
        quay.io/coreos/hyperkube:v1.7.5_coreos.0 \
        --exec=/hyperkube -- proxy \
        --master=http://172.16.0.10:8080
        Restart=always
        RestartSec=10
  update:
    group: stable
    reboot-strategy: off